export const SOCKET_PREFIX = "socket/";
export const KEEPALIVE_LABEL = "keepalive";

export const PULSAR_UFRAG = "pulsar";
export const PULSAR_PWD = "pulsarpulsarpulsarpuls";
export const PULSAR_FINGERPRINT =
  "F1:85:10:8F:36:FF:58:D8:D0:4B:52:D7:ED:DC:5C:28:AE:7D:DB:54:0E:2A:DD:C7:C3:94:EA:A1:27:D0:4E:78";

// werift's signatureHash config for the fixed P-256 certificate.
export const PULSAR_SIGNATURE_HASH = { hash: 4, signature: 3 } as const;

export const PULSAR_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkdA44UARw55aA4wy
Elp/vqaU3wXDh8DBYhAxM/7ZLRahRANCAASuVw5r45AERNd5Ti/DWgXHd7pOxgbr
rFNpgeRvAqI5t3yQ5jOgtHORVN8sg3G6uJWTXm2mHwFnRD+lp3BJI739
-----END PRIVATE KEY-----`;

export const PULSAR_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIBdzCCAR2gAwIBAgIUa60SsYmtqbUvTq6GMnD2hMh1AJIwCgYIKoZIzj0EAwIw
ETEPMA0GA1UEAwwGcHVsc2FyMB4XDTI2MDUxNjE4NTcyMFoXDTM2MDUxMzE4NTcy
MFowETEPMA0GA1UEAwwGcHVsc2FyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
rlcOa+OQBETXeU4vw1oFx3e6TsYG66xTaYHkbwKiObd8kOYzoLRzkVTfLINxuriV
k15tph8BZ0Q/padwSSO9/aNTMFEwHQYDVR0OBBYEFL/9f7vNbXwQxtvek42L+pJ/
jvuNMB8GA1UdIwQYMBaAFL/9f7vNbXwQxtvek42L+pJ/jvuNMA8GA1UdEwEB/wQF
MAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgILT4sZfw9rjX0GPH+onIZneeevHwa6IG
rFlLfzYN+g4CIQCI/+nN1A3TyiUhT6rD7OzT59+l2X1VYHf+2GzrsD8M2Q==
-----END CERTIFICATE-----`;
